--- 
abstract: Make $c->uri_for and $c->req->uri_with return relative URIs
author: 
  - Rafael Kitover <rkitover@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-RelativePaths
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7007
  Class::C3: 0
version: 0.01
